services:
  avkastningskalkylatorn:
    container_name: avkastningskalkylatorn
    build: .
    volumes:
      - ./exports:/exports
      - ./imports:/imports
      - .:/usr/src/avkastningskalkylatorn
