services:
  avkastningskalkylatorn:
    environment:
      - EOD_API_TOKEN=${EOD_API_TOKEN}
    container_name: avkastningskalkylatorn
    build: .
    volumes:
      - ./resources:/resources
      - .:/usr/src/avkastningskalkylatorn
