services:
  avkastningskalkylatorn:
    environment:
      - EOD_API_TOKEN=${EOD_API_TOKEN}
    container_name: avkastningskalkylatorn
    build: .
    volumes:
      - ./exports:/exports
      - ./imports:/imports
      - .:/usr/src/avkastningskalkylatorn
