commands:
  help:
    description: "Prints available commands and their options"

  calculate:
    description: "Calculate profits on investments"
    options:
      export-csv:
        description: "Generate and export CSV file"
        default: false
        require_value: false
      bank:
        description: "Filter on bank(s)"
        require_value: true
      account:
        description: "Filter on account(s)"
        require_value: true
      date-from:
        description: "Filter from <date> (YYYY-MM-DD)"
        require_value: true
      date-to:
        description: "Filter to <date> (YYYY-MM-DD)"
        require_value: true
      asset:
        description: "Filter on asset(s)"
        require_value: true
      isin:
        description: "Filter on ISIN(s)"
        require_value: true
      current-holdings:
        description: "Filter on current holdings"
        default: false
        require_value: false
      verbose:
        description: "Show verbose output"
        default: false
        require_value: false
      overview:
        description: "Show investment overview report"
        default: false
        require_value: false
      display-log:
        description: "Display log messages"
        default: false
        require_value: false
      twr:
        description: "Calculate Time-Weighted Rate of Return"
        require_value: false

  generate-isin-list:
    description: "Generate a list of ISINs in csv format"
    options:
      bank:
        description: "Generate ISIN list on bank(s)"
        require_value: true
      account:
        description: "Generate ISIN list on account(s)"
        require_value: true

  generate-ticker-list:
    description: "Generate a list of tickers in json format to be used in the app"
    options:

  transaction:
    description: "List transactions"
    options:
      export-csv:
        description: "Generate and export CSV file"
        default: false
        require_value: false
      bank:
        description: "Filter on bank(s)"
        require_value: true
      account:
        description: "Filter on account(s)"
        require_value: true
      date-from:
        description: "Filter from <date> (YYYY-MM-DD)"
        require_value: true
      date-to:
        description: "Filter to <date> (YYYY-MM-DD)"
        require_value: true
      type:
        description: "Filter on type"
        require_value: true
      isin:
        description: "Filter on ISIN(s)"
        require_value: true
      current-holdings:
        description: "Filter on current holdings"
        default: false
        require_value: false
      asset:
        description: "Filter on asset(s)"
        require_value: true
      fee:
        description: "Filter on fee"
        require_value: false
      cash-flow:
        description: "Display cash flow"
        require_value: false
      cash-flow-dates:
        description: "Display cash flow dates"
        require_value: false
      display-log:
        description: "Display log messages"
        default: false
        require_value: false

  pp-export:
    description: "Export transactions to Portfolio Performance format"
    options:
      bank:
        description: "Filter on bank(s)"
        require_value: true
      account:
        description: "Filter on account(s)"
        require_value: true
      date-from:
        description: "Filter from <date> (YYYY-MM-DD)"
        require_value: true
      date-to:
        description: "Filter to <date> (YYYY-MM-DD)"
        require_value: true
      type:
        description: "Filter on type"
        require_value: true
      isin:
        description: "Filter on ISIN(s)"
        require_value: true
      asset:
        description: "Filter on asset(s)"
        require_value: true
      display-log:
        description: "Display log messages"
        default: false
        require_value: false
      