name: Update PHPStan Level Gist

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract PHPStan level
        id: phpstan-level
        run: |
          level=$(grep 'level:' ./phpstan/phpstan.neon | cut -d ':' -f2 | xargs)
          echo "::set-output name=level::$level"
      
      - name: Update Gist with GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            const gistId = '${{ secrets.STAN_GIST_ID }}';
            const token = '${{ secrets.GIST_TOKEN }}';
            const headers = {
              'Accept': 'application/vnd.github+json',
              'Authorization': `Bearer ${token}`
            };
      
            const data = {
              description: "An updated gist description",
              files: {
                "README.md": {
                  content: "Hello World from GitHub"
                }
              }
            };
      
            const response = await github.request('PATCH /gists/{gist_id}', {
              gist_id: gistId,
              headers: headers,
              data: data
            });
      
            console.log(response.data);
