name: Update PHPStan Level Gist

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract PHPStan level
        id: phpstan-level
        run: |
          level=$(grep 'level:' ./phpstan/phpstan.neon | cut -d ':' -f2 | xargs)
          echo "::set-output name=level::$level"
      
      - name: Update Gist with GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            const gistId = '${{ secrets.STAN_GIST_ID }}';
            const filename = 'phpstan_badge.json';
            const content = `
            {
              "schemaVersion": 1,
              "label": "phpstan",
              "message": "level ${{ steps.phpstan-level.outputs.level }}",
              "color": "blue"
            }
            `;
            const files = {};
            files[filename] = { content: content };
            
            await github.rest.gists.update({
              gist_id: gistId,
              files: files
            });
