name: Update PHPStan Level Gist

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract PHPStan level
        id: phpstan-level
        run: |
          level=$(grep 'level:' ./phpstan/phpstan.neon | cut -d ':' -f2 | xargs)
          echo "::set-output name=level::$level"

      - name: Update Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Antag att du har lagrat din PAT som GITHUB_TOKEN i secrets
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIST_TOKEN }}" \
            https://api.github.com/gists/${{ secrets.STAN_GIST_ID }} \
            -d '{"description":"Updated gist description via curl","files":{"README.md":{"content":"Hello World from GitHub Actions using curl"}}}'
      
