name: Phan
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP with phan
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          ini-values: xdebug.mode=off
          tools: phan
          coverage: none

      - name: Run Phan (Severity 0)
        run: phan --color --config-file .phan/config.php --long-progress-bar --minimum-severity=0
