name: PHPStan
on:
  workflow_dispatch:
  pull_request:

jobs:
  phpstan-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP with PHPStan
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpstan

      - name: Run PHPStan
        run: phpstan analyse -c .phpstan/phpstan.neon -v
